function output = dominant_frequencies (esd, alpha)
	if nargin < 2
		alpha = 1;
	end
	n = length(esd{1});
	mask = logical(ones(1, n));
	mask(1:2) = false;
	output = cellfun( ...
		@(row) row > ...
			mean(row(2:n)) + ...
			alpha * std(row(2:n)) & ...
			mask, ...
		esd, ...
		'UniformOutput', false);
end
