function output = dominant_frequencies (esd, alpha)
	if nargin < 2
		alpha = 1;
	end
	n = size(esd, 1);
	mask = logical(ones(n, 1));
	mask(1:2) = false;
	output = cell2mat(cellfun( ...
		@(col) col > ...
			mean(col(2:n)) + ...
			alpha * std(col(2:n)) & ...
			mask, ...
		mat2cell(esd, ...
			n, ...
			ones(1, size(esd, 2))), ...
		'UniformOutput', false));
end
