function rss_map = sym_rss_image (im, n)
	rss_map = [];
	[height width] = size(im);
	[xs ys] = meshgrid(1:width, 1:height);
	coords = cell2mat(arrayfun( ...
		@(x, y) (struct('x', x, 'y', y)), ...
		xs, ...
		ys, ...
		'UniformOutput', false));
	rss_map = arrayfun( ...
		@(coord) ( ...
			sym_rss_point(im, coord.x, coord.y, n)), ...
		coords);
end
