function esd = sym_esd (dft_coeffs)
	esd = cell2mat(cellfun(@(col) (col .* conj(col)), ...
		mat2cell(dft_coeffs, ...
			size(dft_coeffs, 1), ...
			ones(1, size(dft_coeffs, 2))), ...
		'UniformOutput', false));
end
